# Generated by Django 2.0.7 on 2018-07-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_requested',
            field=models.DateTimeField(verbose_name='تاریخ ثبت درخواست'),
        ),
    ]
